### ISSUE TITLE
Fill README file

### ISSUE THREAD

**Issue by Artemnsk** [Artemnsk/slackgametest#2]
1. Firebase info (deployment, blaze).
2. Code styling.
3. Other.

**Comment by Artemnsk** [comment]
@guvkon please test. Follow all these steps and let me know if I missed something.

**Comment by Artemnsk** [comment]
btw merged into master already because that's definitely better than nothing 😄

**Comment by guvkon** [comment]
@Artemnsk I've slightly updated readme (e.g. added some more info on Firebase deployment). But I have a couple of questions regarding the app settings:
1. Do I need to add a bot user?
2. Which permissions are needed? And I guess I can keep reinstalling the app when it requires new permissions?

**Comment by guvkon** [comment]
Ok, question 1 I've figured out myself. I do. Otherwise, it fails to be installed in the workspace. I'll update readme with this info.

**Comment by Artemnsk** [comment]
1. Yes, on Slack App you must turn bot user on
2. Currently all permissions live in controllers/authorize/index.js:authorizeRequest()->'scope' property. If you want extra permissions add them there and yes - simply reinstall Slack app in your dev team.

Pls update readme

**Comment by guvkon** [comment]
@Artemnsk updated readme. You might find small changes to https://github.com/Artemnsk/slackgametest#3-install-game-app-in-slack-team quite interesting ;)

**Comment by Artemnsk** [comment]
@guvkon close?
